# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatbotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Conversational = channel.unary_stream(
                '/chatbot.Chatbot/Conversational',
                request_serializer=chat__pb2.ConversationalRequest.SerializeToString,
                response_deserializer=chat__pb2.ConversationalResponse.FromString,
                )


class ChatbotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Conversational(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatbotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Conversational': grpc.unary_stream_rpc_method_handler(
                    servicer.Conversational,
                    request_deserializer=chat__pb2.ConversationalRequest.FromString,
                    response_serializer=chat__pb2.ConversationalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.Chatbot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chatbot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Conversational(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chatbot.Chatbot/Conversational',
            chat__pb2.ConversationalRequest.SerializeToString,
            chat__pb2.ConversationalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
