# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x07\x63hatbot\"<\n\x15\x43onversationalRequest\x12\x14\n\x0csession_uuid\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\"\x84\x02\n\x16\x43onversationalResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.chatbot.ConversationalResponse.Status\x12\r\n\x05token\x18\x02 \x01(\t\x12\x14\n\x0cused_sources\x18\x03 \x03(\t\"\x8c\x01\n\x06Status\x12\n\n\x06UKNOWN\x10\x00\x12\x10\n\x0cLOAD_HISTORY\x10\x01\x12\x0e\n\nWEB_SEARCH\x10\x02\x12\x10\n\x0c\x42UILD_PROMPT\x10\x03\x12\x15\n\x11GENERATE_RESPONSE\x10\x04\x12\x11\n\rUPDATE_MEMORY\x10\x05\x12\x0c\n\x08\x46INISHED\x10\x06\x12\n\n\x06\x46\x41ILED\x10\x07\x32^\n\x07\x43hatbot\x12S\n\x0e\x43onversational\x12\x1e.chatbot.ConversationalRequest\x1a\x1f.chatbot.ConversationalResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONVERSATIONALREQUEST']._serialized_start=23
  _globals['_CONVERSATIONALREQUEST']._serialized_end=83
  _globals['_CONVERSATIONALRESPONSE']._serialized_start=86
  _globals['_CONVERSATIONALRESPONSE']._serialized_end=346
  _globals['_CONVERSATIONALRESPONSE_STATUS']._serialized_start=206
  _globals['_CONVERSATIONALRESPONSE_STATUS']._serialized_end=346
  _globals['_CHATBOT']._serialized_start=348
  _globals['_CHATBOT']._serialized_end=442
# @@protoc_insertion_point(module_scope)
